# Data Exploration
## Exploring CRSP Dataset:

In [1]:
# Importing libraries
import pandas as pd
import matplotlib as plt

In [2]:
crsp_para = pd.read_csv('./data/2023_sp_500_select_50/combined_parameters_raw.csv')
crsp_para

,date,NDSN_RET,NDSN_VOL_CHANGE,NDSN_ASK,NDSN_BID,NDSN_sprtrn,HOLX_RET,HOLX_VOL_CHANGE,HOLX_ASK,HOLX_BID,...,MHK_RET,MHK_VOL_CHANGE,MHK_ASK,MHK_BID,MHK_sprtrn,FDS_RET,FDS_VOL_CHANGE,FDS_ASK,FDS_BID,FDS_sprtrn
0,2007-12-06,0.022113,0.175059,54.08000,53.97000,0.015037,0.032248,-0.416876,64.03,64.02,...,0.024942,-0.405355,79.43,79.35,0.015037,-0.022291,0.480991,63.51000,63.50000,0.015037
1,2007-12-07,0.004438,-0.517405,54.32000,54.21000,-0.001778,0.000156,-0.500919,64.03,63.94,...,0.006809,-0.285097,79.79,79.69,-0.001778,0.009120,0.311163,64.18000,64.09000,-0.001778
2,2007-12-10,0.015832,0.116610,55.24000,55.17000,0.007510,0.014368,-0.435645,64.95,64.92,...,0.022668,-0.157332,81.66,81.60,0.007510,0.014646,-0.310294,65.18000,65.15000,0.007510
3,2007-12-11,-0.045669,0.432598,52.75000,52.67000,-0.025271,-0.022479,0.314073,63.50,63.51,...,-0.031839,2.373966,79.06,78.99,-0.025271,-0.004453,-0.081935,64.83000,64.75000,-0.025271
4,2007-12-12,0.022598,0.106987,53.99000,53.85000,0.006050,0.018271,0.175530,64.76,64.72,...,-0.016190,-0.475887,77.82,77.61,0.006050,0.008792,0.530101,65.35000,65.28000,0.006050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4058,2023-12-22,0.008450,0.038850,261.51001,261.34000,0.001660,-0.000422,0.362391,71.05,71.03,...,0.001554,-0.469528,103.13,103.08,0.001660,-0.002233,-0.483430,468.70001,468.69000,0.001660
4059,2023-12-26,0.010025,-0.405174,263.98999,263.76999,0.004232,0.000985,-0.474035,71.13,71.10,...,-0.004558,0.859960,102.64,102.63,0.004232,0.006778,-0.276786,472.39001,472.38000,0.004232
4060,2023-12-27,0.000795,0.330596,264.23999,264.19000,0.001430,-0.002391,0.842311,70.94,70.92,...,0.009548,-0.086697,103.71,103.62,0.001430,0.004023,-0.101245,474.44000,474.17001,0.001430
4061,2023-12-28,0.001249,-0.075709,264.73001,264.51999,0.000370,0.004511,-0.359484,71.26,71.24,...,0.012063,-0.024619,104.90,104.88,0.000370,0.005441,0.391621,477.13000,477.12000,0.000370
4062,2023-12-29,-0.001361,0.026488,264.20001,264.17001,-0.002826,0.002666,0.294459,71.45,71.44,...,-0.013064,0.129827,103.51,103.50,-0.002826,0.000545,-0.343840,476.66000,476.64999,-0.002826

In [3]:
print('Columns:', crsp_para.columns)
crsp_para.describe()

Columns: Index(['date', 'NDSN_RET', 'NDSN_VOL_CHANGE', 'NDSN_ASK', 'NDSN_BID',
       'NDSN_sprtrn', 'HOLX_RET', 'HOLX_VOL_CHANGE', 'HOLX_ASK', 'HOLX_BID',
       ...
       'MHK_RET', 'MHK_VOL_CHANGE', 'MHK_ASK', 'MHK_BID', 'MHK_sprtrn',
       'FDS_RET', 'FDS_VOL_CHANGE', 'FDS_ASK', 'FDS_BID', 'FDS_sprtrn'],
      dtype='object', length=251)

,NDSN_RET,NDSN_VOL_CHANGE,NDSN_ASK,NDSN_BID,NDSN_sprtrn,HOLX_RET,HOLX_VOL_CHANGE,HOLX_ASK,HOLX_BID,HOLX_sprtrn,...,MHK_RET,MHK_VOL_CHANGE,MHK_ASK,MHK_BID,MHK_sprtrn,FDS_RET,FDS_VOL_CHANGE,FDS_ASK,FDS_BID,FDS_sprtrn
count,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,...,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000
mean,0.000817,0.123234,115.064918,114.980763,0.000370,0.000431,0.119399,39.236778,39.221428,0.000370,...,0.000397,0.099735,125.693889,125.658920,0.000370,0.000658,0.091993,191.645646,191.571523,0.000370
std,0.022026,0.668460,65.728000,65.672068,0.012899,0.020800,0.670880,21.288858,21.284716,0.012899,...,0.026099,0.555480,62.464627,62.461842,0.012899,0.017807,0.613620,123.936774,123.886490,0.012899
min,-0.237286,-0.946604,20.420000,20.400000,-0.119841,-0.205274,-0.881193,9.410000,9.390000,-0.119841,...,-0.242460,-0.843026,17.130000,17.110000,-0.119841,-0.123075,-0.902859,33.260000,33.200000,-0.119841
25%,-0.008192,-0.238444,63.735000,63.665000,-0.004294,-0.008934,-0.241174,20.560000,20.550000,-0.004294,...,-0.011073,-0.231621,69.430000,69.375000,-0.004294,-0.007218,-0.224549,93.320000,93.305000,-0.004294
50%,0.000722,-0.002706,82.540000,82.510000,0.000672,0.000698,-0.016949,37.430000,37.420000,0.000672,...,0.000331,-0.006251,122.440000,122.400000,0.000672,0.001440,-0.017014,159.160000,159.120000,0.000672
75%,0.010579,0.302528,156.270000,156.210000,0.006012,0.009763,0.296620,52.785000,52.765000,0.006012,...,0.011999,0.286015,180.154995,180.100000,0.006012,0.008977,0.269393,278.175000,278.149995,0.006012
max,0.196964,12.797857,270.670010,270.370000,0.115800,0.141047,13.589685,87.670000,87.630000,0.115800,...,0.295611,8.467686,284.790010,284.690000,0.115800,0.177409,22.530243,488.859990,488.850010,0.115800

In [4]:
crsp_predictors = pd.read_csv('./data/2023_sp_500_select_50/combined_predictors_raw.csv')
crsp_predictors

,date,NDSN_BA_SPREAD,NDSN_ILLIQUIDITY,NDSN_TURNOVER,NDSN_VOL_CHANGE,NDSN_RET,NDSN_sprtrn,HOLX_BA_SPREAD,HOLX_ILLIQUIDITY,HOLX_TURNOVER,...,MHK_TURNOVER,MHK_VOL_CHANGE,MHK_RET,MHK_sprtrn,FDS_BA_SPREAD,FDS_ILLIQUIDITY,FDS_TURNOVER,FDS_VOL_CHANGE,FDS_RET,FDS_sprtrn
0,2007-12-06,0.002034,2.047758e-09,5.931001,0.175059,0.022113,0.015037,0.000156,8.561751e-11,46.712145,...,8.807433,-0.405355,0.024942,0.015037,0.000157,-6.816169e-10,10.573502,0.480991,-0.022291,0.015037
1,2007-12-07,0.002025,8.478377e-10,2.862269,-0.517405,0.004438,-0.001778,0.001406,8.297462e-13,23.313159,...,6.296459,-0.285097,0.006809,-0.001778,0.001402,2.107688e-10,13.863585,0.311163,0.009120,-0.001778
2,2007-12-10,0.001269,2.666477e-09,3.196038,0.116610,0.015832,0.007510,0.000462,1.334962e-10,13.156897,...,5.305824,-0.157332,0.022668,0.007510,0.000461,4.836728e-10,9.561802,-0.310294,0.014646,0.007510
3,2007-12-11,0.001519,-5.626003e-09,4.578638,0.432598,-0.045669,-0.025271,-0.000158,-1.625938e-10,17.289125,...,17.901668,2.373966,-0.031839,-0.025271,0.001234,-1.608980e-10,8.778351,-0.081935,-0.004453,-0.025271
4,2007-12-12,0.002600,2.459240e-09,5.068494,0.106987,0.022598,0.006050,0.000619,1.104060e-10,20.323877,...,9.382499,-0.475887,-0.016190,0.006050,0.001070,2.058087e-10,13.431762,0.530101,0.008792,0.006050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4058,2023-12-22,0.000650,1.572889e-10,3.605715,0.038850,0.008450,0.001660,0.000282,-4.281558e-12,5.780840,...,4.584639,-0.469528,0.001554,0.001660,0.000021,-1.898808e-11,6.598847,-0.483430,-0.002233,0.001660
4059,2023-12-26,0.000833,3.106019e-10,2.144772,-0.405174,0.010025,0.004232,0.000422,1.898196e-11,3.040520,...,8.527245,0.859960,-0.004558,0.004232,0.000021,7.915774e-11,4.772375,-0.276786,0.006778,0.004232
4060,2023-12-27,0.000189,1.849674e-11,2.853825,0.330596,0.000795,0.001430,0.000282,-2.507038e-11,5.601584,...,7.787962,-0.086697,0.009548,0.001430,0.000569,5.206633e-11,4.289197,-0.101245,0.004023,0.001430
4061,2023-12-28,0.000794,3.140074e-11,2.637764,-0.075709,0.001249,0.000370,0.000281,7.351389e-11,3.587905,...,7.596228,-0.024619,0.012063,0.000370,0.000021,5.032782e-11,5.968938,0.391621,0.005441,0.000370
4062,2023-12-29,0.000114,-3.337899e-11,2.707632,0.026488,-0.001361,-0.002826,0.000140,3.347434e-11,4.644396,...,8.582425,0.129827,-0.013064,-0.002826,0.000021,7.678551e-12,3.916579,-0.343840,0.000545,-0.002826

In [5]:
# To find columns that are not present in combined_parameters dataset
crsp_para_cols = crsp_para.columns
crsp_predictors_cols = crsp_predictors.columns
diff_in_cols = []
for col in crsp_predictors_cols:
    if col not in crsp_para_cols:
        diff_in_cols.append(col)

print(diff_in_cols)

['NDSN_BA_SPREAD', 'NDSN_ILLIQUIDITY', 'NDSN_TURNOVER', 'HOLX_BA_SPREAD', 'HOLX_ILLIQUIDITY', 'HOLX_TURNOVER', 'ATO_BA_SPREAD', 'ATO_ILLIQUIDITY', 'ATO_TURNOVER', 'KIM_BA_SPREAD', 'KIM_ILLIQUIDITY', 'KIM_TURNOVER', 'NVR_BA_SPREAD', 'NVR_ILLIQUIDITY', 'NVR_TURNOVER', 'DPZ_BA_SPREAD', 'DPZ_ILLIQUIDITY', 'DPZ_TURNOVER', 'JBHT_BA_SPREAD', 'JBHT_ILLIQUIDITY', 'JBHT_TURNOVER', 'DECK_BA_SPREAD', 'DECK_ILLIQUIDITY', 'DECK_TURNOVER', 'FRT_BA_SPREAD', 'FRT_ILLIQUIDITY', 'FRT_TURNOVER', 'KMX_BA_SPREAD', 'KMX_ILLIQUIDITY', 'KMX_TURNOVER', 'EXR_BA_SPREAD', 'EXR_ILLIQUIDITY', 'EXR_TURNOVER', 'LNT_BA_SPREAD', 'LNT_ILLIQUIDITY', 'LNT_TURNOVER', 'CINF_BA_SPREAD', 'CINF_ILLIQUIDITY', 'CINF_TURNOVER', 'ED_BA_SPREAD', 'ED_ILLIQUIDITY', 'ED_TURNOVER', 'REG_BA_SPREAD', 'REG_ILLIQUIDITY', 'REG_TURNOVER', 'CPB_BA_SPREAD', 'CPB_ILLIQUIDITY', 'CPB_TURNOVER', 'LH_BA_SPREAD', 'LH_ILLIQUIDITY', 'LH_TURNOVER', 'TRMB_BA_SPREAD', 'TRMB_ILLIQUIDITY', 'TRMB_TURNOVER', 'DVA_BA_SPREAD', 'DVA_ILLIQUIDITY', 'DVA_TURNOVER', 'PKG_BA_SPREAD', 'PKG_ILLIQUIDITY', 'PKG_TURNOVER', 'CAG_BA_SPREAD', 'CAG_ILLIQUIDITY', 'CAG_TURNOVER', 'NTRS_BA_SPREAD', 'NTRS_ILLIQUIDITY', 'NTRS_TURNOVER', 'KMB_BA_SPREAD', 'KMB_ILLIQUIDITY', 'KMB_TURNOVER', 'TRV_BA_SPREAD', 'TRV_ILLIQUIDITY', 'TRV_TURNOVER', 'RHI_BA_SPREAD', 'RHI_ILLIQUIDITY', 'RHI_TURNOVER', 'UHS_BA_SPREAD', 'UHS_ILLIQUIDITY', 'UHS_TURNOVER', 'EMN_BA_SPREAD', 'EMN_ILLIQUIDITY', 'EMN_TURNOVER', 'PODD_BA_SPREAD', 'PODD_ILLIQUIDITY', 'PODD_TURNOVER', 'TECH_BA_SPREAD', 'TECH_ILLIQUIDITY', 'TECH_TURNOVER', 'EXPD_BA_SPREAD', 'EXPD_ILLIQUIDITY', 'EXPD_TURNOVER', 'WRB_BA_SPREAD', 'WRB_ILLIQUIDITY', 'WRB_TURNOVER', 'EIX_BA_SPREAD', 'EIX_ILLIQUIDITY', 'EIX_TURNOVER', 'STLD_BA_SPREAD', 'STLD_ILLIQUIDITY', 'STLD_TURNOVER', 'BXP_BA_SPREAD', 'BXP_ILLIQUIDITY', 'BXP_TURNOVER', 'CHRW_BA_SPREAD', 'CHRW_ILLIQUIDITY', 'CHRW_TURNOVER', 'IVZ_BA_SPREAD', 'IVZ_ILLIQUIDITY', 'IVZ_TURNOVER', 'HSIC_BA_SPREAD', 'HSIC_ILLIQUIDITY', 'HSIC_TURNOVER', 'TFX_BA_SPREAD', 'TFX_ILLIQUIDITY', 'TFX_TURNOVER', 'AKAM_BA_SPREAD', 'AKAM_ILLIQUIDITY', 'AKAM_TURNOVER', 'JKHY_BA_SPREAD', 'JKHY_ILLIQUIDITY', 'JKHY_TURNOVER', 'HBAN_BA_SPREAD', 'HBAN_ILLIQUIDITY', 'HBAN_TURNOVER', 'ESS_BA_SPREAD', 'ESS_ILLIQUIDITY', 'ESS_TURNOVER', 'ETR_BA_SPREAD', 'ETR_ILLIQUIDITY', 'ETR_TURNOVER', 'FFIV_BA_SPREAD', 'FFIV_ILLIQUIDITY', 'FFIV_TURNOVER', 'CPT_BA_SPREAD', 'CPT_ILLIQUIDITY', 'CPT_TURNOVER', 'IEX_BA_SPREAD', 'IEX_ILLIQUIDITY', 'IEX_TURNOVER', 'IRM_BA_SPREAD', 'IRM_ILLIQUIDITY', 'IRM_TURNOVER', 'COO_BA_SPREAD', 'COO_ILLIQUIDITY', 'COO_TURNOVER', 'MHK_BA_SPREAD', 'MHK_ILLIQUIDITY', 'MHK_TURNOVER', 'FDS_BA_SPREAD', 'FDS_ILLIQUIDITY', 'FDS_TURNOVER']

In [6]:
# To find all tickers and features present in the datasets
tickers = []
features = []
for col in crsp_para_cols:
    if col != 'date':
        ticker = col.split("_", 1)[0]
        tickers.append(ticker)

        feature = col.split("_", 1)[1]
        features.append(feature)

tickers = set(sorted(tickers))
features = set(sorted(features))
print('Tickers present in parameters:', set(sorted(tickers)), '\n')
print('Feature present in parameters:', set(sorted(features)), '\n')

print('-' * 100)
tickers = []
features = []
for col in crsp_predictors_cols:
    if col != 'date':
        ticker = col.split("_", 1)[0]
        tickers.append(ticker)

        feature = col.split("_", 1)[1]
        features.append(feature)

tickers = set(sorted(tickers))
features = set(sorted(features))
print('Tickers present in predictors:', tickers, '\n')
print('Feature present in predictors:', features, '\n')

Tickers present in parameters: {'JKHY', 'EIX', 'FFIV', 'ATO', 'ESS', 'CPB', 'NDSN', 'EMN', 'DVA', 'KMX', 'MHK', 'CHRW', 'CPT', 'FDS', 'PODD', 'IEX', 'STLD', 'TRMB', 'EXPD', 'KIM', 'EXR', 'NTRS', 'HBAN', 'UHS', 'KMB', 'IRM', 'WRB', 'BXP', 'NVR', 'TRV', 'FRT', 'LH', 'TECH', 'ED', 'DPZ', 'REG', 'HOLX', 'CAG', 'AKAM', 'COO', 'DECK', 'HSIC', 'IVZ', 'CINF', 'ETR', 'PKG', 'RHI', 'LNT', 'TFX', 'JBHT'}

Feature present in parameters: {'RET', 'VOL_CHANGE', 'BID', 'ASK', 'sprtrn'}

----------------------------------------------------------------------------------------------------
Tickers present in predictors: {'JKHY', 'EIX', 'FFIV', 'ATO', 'ESS', 'CPB', 'NDSN', 'EMN', 'DVA', 'KMX', 'MHK', 'CHRW', 'CPT', 'FDS', 'PODD', 'IEX', 'STLD', 'TRMB', 'EXPD', 'KIM', 'EXR', 'NTRS', 'HBAN', 'UHS', 'KMB', 'IRM', 'WRB', 'BXP', 'NVR', 'TRV', 'FRT', 'LH', 'TECH', 'ED', 'DPZ', 'REG', 'HOLX', 'CAG', 'AKAM', 'COO', 'DECK', 'HSIC', 'IVZ', 'CINF', 'ETR', 'PKG', 'RHI', 'LNT', 'TFX', 'JBHT'}

Feature present in predictors: {'RET', 'BA_SPREAD', 'VOL_CHANGE', 'TURNOVER', 'ILLIQUIDITY', 'sprtrn'}

In [7]:
print('Number of tickers present in dataset:', len(tickers))

Number of tickers present in dataset: 50

In [9]:
crsp_predictors.describe()

,NDSN_BA_SPREAD,NDSN_ILLIQUIDITY,NDSN_TURNOVER,NDSN_VOL_CHANGE,NDSN_RET,NDSN_sprtrn,HOLX_BA_SPREAD,HOLX_ILLIQUIDITY,HOLX_TURNOVER,HOLX_VOL_CHANGE,...,MHK_TURNOVER,MHK_VOL_CHANGE,MHK_RET,MHK_sprtrn,FDS_BA_SPREAD,FDS_ILLIQUIDITY,FDS_TURNOVER,FDS_VOL_CHANGE,FDS_RET,FDS_sprtrn
count,4063.000000,4.063000e+03,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4.063000e+03,4063.000000,4063.000000,...,4063.000000,4063.000000,4063.000000,4063.000000,4063.000000,4.063000e+03,4063.000000,4063.000000,4063.000000,4063.000000
mean,0.000731,2.523047e-11,5.333412,0.123234,0.000817,0.000370,0.000483,3.618645e-12,10.546908,0.119399,...,10.969936,0.099735,0.000397,0.000370,0.000445,2.500511e-11,8.393459,0.091993,0.000658,0.000370
std,0.000924,1.369954e-09,5.655484,0.668460,0.022026,0.012899,0.000751,3.025490e-10,9.341115,0.670880,...,7.994182,0.555480,0.026099,0.012899,0.000754,4.266981e-10,6.243206,0.613620,0.017807,0.012899
min,-0.000900,-1.137370e-08,0.868338,-0.946604,-0.237286,-0.119841,-0.003477,-2.612447e-09,1.010127,-0.881193,...,1.153196,-0.843026,-0.242460,-0.119841,-0.000824,-3.979247e-09,1.125874,-0.902859,-0.123075,-0.119841
25%,0.000296,-3.448154e-10,3.011700,-0.238444,-0.008192,-0.004294,0.000249,-1.126423e-10,5.978874,-0.241174,...,6.660204,-0.231621,-0.011073,-0.004294,0.000107,-1.465242e-10,5.198576,-0.224549,-0.007218,-0.004294
50%,0.000547,2.811881e-11,4.135430,-0.002706,0.000722,0.000672,0.000391,8.336262e-12,8.246029,-0.016949,...,9.116171,-0.006251,0.000331,0.000672,0.000267,2.619031e-11,6.857402,-0.017014,0.001440,0.000672
75%,0.000917,4.275895e-10,6.085259,0.302528,0.010579,0.006012,0.000551,1.236822e-10,12.111006,0.296620,...,12.916707,0.286015,0.011999,0.006012,0.000542,1.952939e-10,9.573205,0.269393,0.008977,0.006012
max,0.041027,1.998784e-08,222.055021,12.797857,0.196964,0.115800,0.038359,2.830953e-09,212.439996,13.589685,...,165.521675,8.467686,0.295611,0.115800,0.016359,2.766379e-09,169.800064,22.530243,0.177409,0.115800

In [22]:
print('First available date:', crsp_predictors['date'].min())
print('Last available date:', crsp_predictors['date'].max())

First available date: 2007-12-06
Last available date: 2023-12-29

In [ ]:
# Missing values check
crsp_predictors.isna().any()